/**
 * Express Router for handling appointments
 * Mounted on /appointment
 * @author JJ
 * @module take routes
 */

const express = require("express");
const router = express.Router();
const sendMail = require("../utils/sendMail");
const fs = require("../utils/fs");
const unixseconds = require("unixseconds");
const { asyncWrap } = require("express-error-middlewares");
const {
  createAndInsertEvent,
  deleteEvent,
} = require("../utils/GoogleCalendar");

// Checks if user already have an account, if true, return account ID,
// Else create a new account and return the ID
async function getUserAccountIdIfExists(phoneNumber) {
  const snapshot = await fs
    .collection("users")
    .where("number", "==", phoneNumber)
    .get();

  // If the snapshot is empty, return undefined to specify user does not have an account
  // Else assume only 1 document for that user, and return the document ID of the user document (the first one)
  if (snapshot.empty) return undefined;
  else return snapshot.docs[0].id;
}

// Creates a new user account and returns the user document ID
async function createUserAccount({ fname, lname, number, email }) {
  // Add first to get user document ID
  // The documents are not keyed using email as it can change, they are keyed using firestore autogenerated UID
  const { id } = await fs.collection("users").add({
    fname,
    lname,
    number,
    email,

    // Store time user account is created in unix seconds (this is the time of the server executing the code)
    createdAt: unixseconds(),
  });

  return id;
}

/**
 * Creates an account for the user if it does not already exists, and book a appointment
 * @name POST /appointment/book
 * @returns Sucess indicator
 */
router.post(
  "/book",
  express.json(),
  asyncWrap(async (req, res) => {
    const { token, dogID, time, fname, lname, email } = req.body;

    if (!token) throw new Error("Missing recaptcha token!");

    // Lazily loading the HTTP client library to help with serverless cold start time
    const recaptchaRes = await require("tiny-json-http")
      .post({
        // No freaking idea why but sending data over as a req.body JSON does not work
        // Need to put all the parameters as query string params which is kinda weird...
        // But I have spent too much time on this and since the below works, just sticking with it
        // url: "https://www.google.com/recaptcha/api/siteverify",
        // data: {
        //   secret: process.env.recaptchaSecret,
        //   response: token,
        //   remoteip: req.headers["x-forwarded-for"] || req.socket.remoteAddress,
        // },

        url: `https://www.google.com/recaptcha/api/siteverify?secret=${
          process.env.recaptchaSecret
        }&response=${token}&remoteip=${
          req.headers["x-forwarded-for"] || req.socket.remoteAddress
        }`,
      })
      .then((resp) => resp.body);

    if (!recaptchaRes.success) throw new Error(recaptchaRes["error-codes"]);
    if (recaptchaRes.score < 0.6)
      throw new Error(`Recaptcha score too low: ${recaptchaRes.score}`);

    // Remove all white space from phone number
    const number = req.body.number.replace(" ", "");

    // Get the user ID either from an existing account, or from a newly created account
    const userID =
      (await getUserAccountIdIfExists(number)) ||
      (await createUserAccount({ fname, lname, number, email }));

    // @todo Handle on failure and still store appointment into DB + notify developer
    // Get the event ID back and store it to programmatically delete or modify it later on if needed
    // Add appointment event to google cal first to get back the event ID to store in appointment doc
    // However by doing this first, means that the appointment ID cannot be added into the description
    // https://developers.google.com/calendar/api/v3/reference/events#id
    const googleCalendarEventID = await createAndInsertEvent({
      start: time,

      summary: `Appointment with ${fname}`,
      description: "Checkout this appointment in the admin portal",
      // description: `AppointmentID: ${appointmentID}\nPortal's link`,
    });

    const { id: appointmentID } = await fs.collection("appointments").add({
      user: userID,

      // Although the `googleCalendarEventID` can be used as the doc ID for appointments, it is safer because,
      // 1. If google calendar API call failed, the appointment data should still be stored
      // 2. If there is ever a time to store appointment directly into the DB its easier to let firestore auto generate
      // 3. It is better to keep these 2 seperate and not have our appointments DB rely on google cal for doc ID
      googleCalendarEventID,

      dogID,
      time,
      fname,
      lname,
      number,
      email,

      // Store time appointment was created in unix seconds (this is the time of the server executing the code)
      createdAt: unixseconds(),
    });

    // Send user a email to confirm with them that their appointment has been scheduled successfully
    await sendMail.send({
      to: email,
      from: process.env.notificationEmailSender,
      subject: "Ministry Of Pup: Appointment Booked!",
      html:
        `Hi ${fname}!<br /><br />` +
        `You appointment has been scheduled successfully, see you on ${new Date(
          time
        )}<br />`,
    });

    // appointmentID is returned so that the booking app can generate the calendar event,
    // with a link for cancelling appointment using this appointmentID
    res.status(200).json({ ok: true, appointmentID });
  })
);

/**
 * Cancel an existing appointment and delete the event in google calendar.
 * This is a POST request instead of a DELETE request to not deal with handling CORS preflight request for DELETE methods.
 * @name POST /appointment/cancel/:appointmentID
 * @returns Sucess indicator
 */
router.post(
  "/cancel/:appointmentID",
  asyncWrap(async (req, res) => {
    const { appointmentID } = req.params;

    const docRef = fs.collection("appointments").doc(appointmentID);

    // Keeping user data for future use and analytics, just adding a cancelled field
    await docRef.update({ cancelled: true });

    // Get the `googleCalendarEventID` from doc to delete the event from google calendar
    const doc = await docRef.get();
    if (!doc.exists) throw new Error("Appointment does not exist in DB");

    await deleteEvent(doc.data().googleCalendarEventID);

    res.status(200).json({ ok: true });
  })
);

module.exports = router;
