/**
 * Converts a date string into milliseconds
 * @param {String} dateString A date string that is generated by HTML input element type="date"
 * @returns {Number} Milliseconds representation of the given date
 */
module.exports = function convertDateToMilliseconds(dateString) {
  // Load this module asynchronously as needed
  // Will be cached after first load
  const { DateTime } = require("luxon");

  // For HTML input element type="date" the values are in the format of "yyyy-mm-dd"
  // The format for luxon format tokens can be found here
  // https://moment.github.io/luxon/#/parsing?id=table-of-tokens
  // And "yyyy-mm-dd" is represented by "yyyy-LL-dd"
  return DateTime.fromFormat(dateString, "yyyy-LL-dd").toMillis();
};
