// Creates a new user account and returns the user document ID
// fname, lname, number, email
async function createUserAccount(userDetails) {
  // The documents are not keyed using email as it can change, they are keyed using firestore autogenerated UID
  // Store time user account is created in unix seconds (this is the time of the server executing the code)
  const { id } = await fs
    .collection("users")
    .add({ ...userDetails, createdAt: unixseconds() });

  return id;
}

/**
 * Create account if does not exists and get back customer/user object
 * @param {*} userID
 * @param {*} customer
 * @returns
 */
const createUserAccountIfDoesNotExist = async (userID, customer) =>
  userID
    ? await require("../utils/getUserAccount").getUserAccount(userID)
    : (await require("../utils/createUserAccount")(customer)) && customer;

module.exports = { createUserAccount, createUserAccountIfDoesNotExist };
